colors:
  primary:
     background: '#151515'
     foreground: '#E8E3E3'

  normal:
    black:   '#101010'
    red:     '#B66467'
    green:   '#8C977D'
    yellow:  '#D9BC8C'
    blue:    '#8DA3B9'
    magenta: '#A988B0'
    cyan:    '#8AA6A2'
    white:   '#E8E3E3'

  bright:
    black:   '#353535'
    red:     '#B66467'
    green:   '#8C977D'
    yellow:  '#D9BC8C'
    blue:    '#8DA3B9'
    magenta: '#A988B0'
    cyan:    '#8AA6A2'
    white:   '#E8E3E3'

window:
  opacity: 1.0
  padding:
    x: 12
    y: 12
  dynamic_padding: true

font:
  normal:
    family: JetBrains Mono
    style: Regular

  bold:
    family: JetBrains Mono
    style: Bold

  italic:
    family: JetBrains Mono
    style: Italic

  bold_italic:
    family: JetBrains Mono
    style: Bold Italic

  size: 11

cursor:
  style:
    shape: Underline
  vi_mode_style:
    shape: Block

env:
  TERM: xterm-256color

